### ISSUE TITLE
Windows App: Application hard crashes with the following errors

### ISSUE THREAD

**Issue by arjunsrinivasan1997** [flickr-downloadr/flickr-downloadr-gtk#141]
I am trying to run this program on a windows 10 computer with a Rayzen 5 5600x. The program connects to my account fine, and starts downloading alright, but crashes after downloading 1% of my 6300 photos.

The following errors were found via the event viewer.

`Application: flickr-downloadr.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.EndGetResponse(System.IAsyncResult)
   at System.Threading.Tasks.TaskFactory`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.__Canon>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.__Canon>, Boolean)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.OAuth.OAuthManager+<MakeAuthenticatedRequestAsync>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Logic.OriginalTagsLogic+<GetOriginalTagsTask>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Logic.DownloadLogic+<DownloadPhotos>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Logic.DownloadLogic+<Download>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Logic.BrowserLogic+<Download>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Presentation.BrowserPresenter+<DownloadPhotos>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.Presentation.BrowserPresenter+<DownloadAllPages>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at FloydPink.Flickr.Downloadr.UI.Windows.BrowserWindow+<buttonDownloadAllPagesClick>d__80.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

`

`Faulting application name: flickr-downloadr.exe, version: 3.4.5.1, time stamp: 0x61e33890
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2130, time stamp: 0x3206f737
Exception code: 0xe0434352
Fault offset: 0x0012df72
Faulting process id: 0x17ac
Faulting application start time: 0x01d8ef01a7d6301d
Faulting application path: C:\Program Files (x86)\flickrdownloadr\flickr-downloadr.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0eebfd2f-0a1c-4354-b79d-c914068c7e0c
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by arjunsrinivasan1997** [comment]
Was able to mostly resolve this by resetting settings to default, though I'm unsure as to which setting I changed that caused this
