### ISSUE TITLE
App crash after authenticating on Windows 7 OS

### ISSUE THREAD

**Issue by kulz9** [flickr-downloadr/flickr-downloadr-gtk#77]
Once authenticated, the app tries to load and raises a Unhandled exception.
The error message is "Please raise an issue on the Support website."

**Comment by kulz9** [comment]
Here is the log:
****
> <log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1525856088834" level="INFO" thread="1"><log4j:message>Application Start.</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="ZOHWIN864PLP" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DSONE\zoh" /><log4j:data name="log4net:HostName" value="ZOHWIN864PLP" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="Main" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1525856088878" level="INFO" thread="1"><log4j:message>Found GTK# version 2.12.26</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="ZOHWIN864PLP" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DSONE\zoh" /><log4j:data name="log4net:HostName" value="ZOHWIN864PLP" /></log4j:properties><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="CheckWindowsGtk" file="" line="0" /></log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1525856090929" level="FATAL" thread="1"><log4j:message>Unhandled Exception.</log4j:message><log4j:properties><log4j:data name="log4jmachinename" value="ZOHWIN864PLP" /><log4j:data name="log4japp" value="flickr-downloadr.exe" /><log4j:data name="log4net:Identity" value="" /><log4j:data name="log4net:UserName" value="DSONE\zoh" /><log4j:data name="log4net:HostName" value="ZOHWIN864PLP" /></log4j:properties><log4j:throwable><![CDATA[System.ArgumentOutOfRangeException: Capacity must be positive.
Parameter name: capacity
   at System.IO.MemoryStream..ctor(Int32 capacity)
   at FloydPink.Flickr.Downloadr.UI.CachedImage.WebResponseExtension.ReadToEnd(WebResponse webresponse)
   at FloydPink.Flickr.Downloadr.UI.CachedImage.HttpHelper.Get(String url)
   at FloydPink.Flickr.Downloadr.UI.CachedImage.HttpHelper.GetAndSaveToFile(String url, String fileName)
   at FloydPink.Flickr.Downloadr.UI.CachedImage.FileCache.FromUrl(String url)
   at FloydPink.Flickr.Downloadr.UI.CachedImage.ImageExtension.SetCachedImage(Image self, String imageUrl)
   at FloydPink.Flickr.Downloadr.UI.Windows.LoginWindow.<>c__DisplayClass6_0.<SetWelcomeLabel>b__0(Object <sender>, EventArgs <e>)
   at Gtk.Application.InvokeCB.Invoke()
   at GLib.Timeout.TimeoutProxy.Handler()]]></log4j:throwable><log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="OnUnhandledException" file="" line="0" /></log4j:event>

**Comment by floydpink** [comment]
Can you please change the logging level to `ALL` from preferences window and paste the output (see here: https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/50#issuecomment-292722777)
